version: "3.8"

services:
  backend:
    build:
      context: ./subscription-api
    volumes:
      - .:/app3   
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./subscription-app
    ports:
      - 80:80
    depends_on:
      - backend



